version: '2.1'
orbs:
  snyk: snyk/snyk@2.2.0
jobs:
    build:
      docker:
        - image: cimg/openjdk:23.0.1
      steps:
        - checkout
        - run: mvn install
        - snyk/scan:
            fail-on-issues: false
workflows: null
