version: '2.1'
orbs:
  snyk: snyk/snyk@2.2.0
jobs:
  snyk-scan:
    build:
    docker:
      - image: cimg/open jdk:11.0
    steps:
      - checkout
      - run: mvn install
      - snyk/scan:
        fail-on-issues: false
        
workflows:
  build-test-snyk:
    jobs:
      - snyk-scan
