name: Snyk Scan (External Shared Action)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  monitor:
    uses: mimidas-snyk/snyk-shared-action/.github/workflows/snyk-node-shared-action.yml@main
    with:
      SNYK_ORG: dc9e71be-cc1d-4b7a-87bf-6640adf930ee
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
